### ISSUE TITLE
Add home reset delay preference

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#13]
Currently, the home reset delay is hardcoded to about 3 seconds after pressing any switch. However, an inverse scanning user would find it really hard to access Tecla as the app would continually send them Home when trying to do anything. Therefore, the home reset event has been disabled for inverse scanning until a preference is exposed.

**Comment by ijdoc** [comment]
This will need a custom pop-up to let users know when Home is about to be called. This will also be useful for #16

**Comment by vishesh04** [comment]
HI I have implemented preference to set timeout for full reset to home,but I m not getting the event when full reset happens.with inverse scanning enabled I have kept on pressing screen for large time(more than 3 seconds) ,but it doesn't reset to home.Is it disabled by default somewhere.Please help.

**Comment by ijdoc** [comment]
@vishesh04 please post a link to the branch you are working on. It is pretty likely the HOME reset is disabled by default in inverse scanning because it would otherwise cause a conflict. This feature can also potentially conflict with #16, so we need to be careful about how it is resolved. Note my comment before:

> This will need a custom pop-up to let users know when Home is about to be called.

**Comment by vishesh04** [comment]
@jorgesilva  link to my repo https://github.com/vishesh04/TeclaAccess . In your comment do you mean ,each time there will be popup when user long presses switch.In the original code there was a comment to turn it into preference.
