### ISSUE TITLE
Contribution names shouldn't be clickable

### ISSUE THREAD

**Issue by k22mak** [KomodoOpenLab/TeclaAccess#133]
Contributor names should not be clickable, but allow for highlight. Will error if clicked.

**Comment by ijdoc** [comment]
@k22mak can you please check that this issue is still solved? With the recent reverts, the issue seems to have been automatically re-opened but I don't think the fix got undone. Just confirm this fix is still valid in develop so I can manually close the issue.

**Comment by k22mak** [comment]
Issue has been fixed, names are not clickable, are highlightable and will not produce an error when attempted to be clicked/selected.
