### ISSUE TITLE
Tecla Access app crashing when combining dictation and typing

### ISSUE THREAD

**Issue by oranje** [KomodoOpenLab/TeclaAccess#139]
When creating a text message in Galaxy Note combining dictation and typing for editing the Tecla Access app crashes. Requiring the user to press pop-up message before the app is restarted.

Tecla Access App 0.9-beta
Voice Search 2.1.4

**Comment by oranje** [comment]
If the user dictates all the text and then edits the app doesn't crash, but if the user combines dictation and text editing it crashes.

**Comment by ijdoc** [comment]
@oranje does that mean it crashes on the second time the user calls upon speech recognition?

**Comment by oranje** [comment]
It's not consistent, might happen after the 2nd or 3rd time speech recognition is called if editing with keyboard in between calls to SR app.

**Comment by k22mak** [comment]
@jorgesilva I've tried to recreate the issue without success under the following specs:

Phone: LG Nexus 4
Voice Search: Unknown (Built in)
Tecla Version: 0.9 beta
Version: Jelly Bean 4.2.2 

Phone: Galaxy SIIX
Voice Search: 2.1.3 
Tecla Version: 0.9 beta
Version: Gingerbread 2.3.5

Steps Attempted
1) Connect to TeclaShield through TeclaApp
2) Start with either dictation, text using joystick or using touchscreen keyboard
3) Use one of the alternative methods to append text
4) Repeated step 2 and 3 multiple times
5) Attempted to delete, followed by appending more text

**Comment by ijdoc** [comment]
@k22mak under your reported step 3, what do you mean by "one of the alternative inputs"?

You need to use the voice input key to engage speech recognition.

**Comment by k22mak** [comment]
ie, If i started off the voice input key (2), I would move to either the touch screen or joystick to type/edit (3).

**Comment by ijdoc** [comment]
Doesn't seem to be reported any more, so will be closing the issue and preparing the release.
