### ISSUE TITLE
BT does not disconnect when unchecked

### ISSUE THREAD

**Issue by k22mak** [KomodoOpenLab/TeclaAccess#140]
The bluetooth does not disconnect from the shield when unchecked in the preference screen. Bug occurs under the version in the develop branch.

Steps to recreate:
1. Connect phone with shield via bluetooth in the tecla preference screen.
2. After connection, press the connection checkbox again to attempt to disconnect.

**Comment by k22mak** [comment]
Bug only occurs as part of the move of the SEP Issue #130. Issue will be resolved when #130 is complete.

**Comment by ijdoc** [comment]
Can you post the repo/branch where this occurs in case it is on github?

**Comment by k22mak** [comment]
It is under my fork of TeclaAccess under the SEP branch. The error occurs in the check for whether SEP is running in TeclaPrefs.java (line 765 - 770)

Here's the link to the repo.
https://github.com/k22mak/TeclaAccess/tree/SEP
