### ISSUE TITLE
Waiting time for repeating keys via the Shield should be reset

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#146]
Carolyn reported she can only type a character 3 times before the waiting time for repeating keys expires.

**Comment by sagar-chandarana** [comment]
I am able to locate the code lines where the issue may reside. But I am confused what is it meant by 'Repeating Keys'?
1) Does it mean that the Self-Scanning (Highlighting) of keys is not delayed when a key is pressed, scanning goes on and on, leaving no extra time for pressing the same key again and again.
or
2) 'Repeating key press' for the characters is also allowed but not working properly. (But in
ca.idi.tekla.ime.TeclaIME.selectHighlighted(Boolean repeat) , 
it says 'Repeat is only implemented for Navigation Keys')

Please guide me.

**Comment by ijdoc** [comment]
It is more as in your second interpretation. The delay existed but was not
reset after a key selection, so users could not select the same key more
than a handful of times before the highlight reset.

This issue has been resolved in the last build though (inside the tags
folder on jorgesilva's fork). We are just waiting for user feedback to
confirm the solution.

**Comment by sagar-chandarana** [comment]
Ohk.. At this point I've almost gone through the whole code. Could you please direct me to an issue or an enhancement on which I can work on?

**Comment by ijdoc** [comment]
Fixed on develop branch already
