### ISSUE TITLE
Speakerphone not automatically activated when placing a call

### ISSUE THREAD

**Issue by MrKevinBarton** [KomodoOpenLab/TeclaAccess#156]
Speakerphone is not automatically activated on Samsung galaxy exhibit 4G when placing a call through the impact dialer widget or by voice command.  Always use speakerphone is checked within the Tecla Access App settings.

**Comment by ijdoc** [comment]
@MrKevinBarton please download and install the latest build from the link below and let us know if the issue still exists:

https://github.com/idrc/TeclaAccess/blob/develop/tags/TeclaAccess_versioncode27_hotfix126.apk

**Comment by MrKevinBarton** [comment]
I downloaded and installed the latest build from the link above but it did not fix the problem. Speakerphone is still not automatically activated when placing a call.

**Comment by ijdoc** [comment]
@MrKevinBarton we'll test with our phones this week to make sure this is happening across all the devices... it may be possible this is only happening with your device. Would you mind sharing the make and model?

**Comment by MrKevinBarton** [comment]
It's a Samsung Galaxy Exhibit ii 4G SGH-T679.  Thanks!

**Comment by ijdoc** [comment]
Just realized the problem is that this happens when the call is placed, not when it is received, which is the only instance where Tecla is forcing the speakerphone on. The app needs to add a listener for outgoing calls so that the speakerphone is used according to the sate of the checkbox.

**Comment by MrKevinBarton** [comment]
Yes, the speakerphone is activated when answering calls. The problem is only when placing calls.

**Comment by sagar-chandarana** [comment]
I looked into the code and the issue. I guess I will add the listener in SwitchEventProvider class. Please correct me if I am wrong.

**Comment by ijdoc** [comment]
@sagarchandarana123 that is correct, you can add the code to the same mReceiver already used for managing outgoing calls

**Comment by sagar-chandarana** [comment]
@jorgesilva code attached in pull request-issue #176 
One more thing, In framework->TeclaApp.answerCall() , line no 186 and 187 are as follows:
1.    TeclaApp.persistence.isSpeakerphoneEnabled();
2.    useSpeakerphone();

It means Speakerphone will be activated no matter what are the preferences. I checked on Galaxy SII and it happens. 
Shouldn't it be: 
186.    if (TeclaApp.persistence.isSpeakerphoneEnabled())
187.          useSpeakerphone();

**Comment by ijdoc** [comment]
Good point Sagar, please fix it in the same branch, it should automatically update the pull request. Thanks!

**Comment by sagar-chandarana** [comment]
Done!

**Comment by ijdoc** [comment]
great, will prepare a quick build right after killing one more bug so @MrKevinBarton can test it
