### ISSUE TITLE
Add repeat lock key to navigation keyboard

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#16]
UPDATE: This issue has been re-written to follow the better solution proposed by Jan Richards and the AEGIS Euro team. The suggestion involves adding a repeat lock key to the navigation keyboard instead of repeating on hold. This is a suitable solution to the conflict with hold actions already available in Tecla and can also be used with inverse scanning!

--- DEPRECATED REPORT BELOW ---
From: https://blueprints.launchpad.net/meadl/+spec/repeat-key-onhold

This feature would allow users to navigate menus without having to keep clicking the same switch, if the user presses and holds a switch that action will be repeated until he/she stops pressing the switch.

**Comment by ijdoc** [comment]
Jan Richards from the Inclusive Design Research Centre has suggested a potentially better approach to this after receiving feedback from the AEGIS Europe group. The suggestion involves adding a repeat lock key to the navigation keyboard instead of repeating on hold. This is a suitable solution to the conflict with hold actions already available in Tecla and can also be used with inverse scanning!

**Comment by ijdoc** [comment]
This issue is related to #89 in that the current voice input key on the navigation keyboard will be placed where the future ALT navigation key will end up. This will allow us to arrange the layout of the keyboard before adding the secondary one.

**Comment by ankitdaf** [comment]
Commit b10a38bb74b2dc9eec7ebf25cc1208c47a652ba5 almost fixes this. Just need to handle the onTouchListener for the view, this commit currently handles only the touch events to the KeyboardView
