### ISSUE TITLE
Shield does not disconnect properly

### ISSUE THREAD

**Issue by k22mak** [KomodoOpenLab/TeclaAccess#169]
The shield shows the wrong message when disconnecting from shield when preference is unchecked. It currently shows "Tecla Shield Connected" where as it should be showing "Tecla Shield disconnected." 

Steps to Recreate
1) Turn on bluetooth
2) Set Tecla as the IME
3) Connect to the shield as normal (box should be checked off)
4) Uncheck the "Connect to Tecla Shield" box

Error Log
![errorlog](https://f.cloud.github.com/assets/2350450/224852/4fc1ce70-85e1-11e2-887f-393d348db43b.png)

**Comment by ijdoc** [comment]
@k22mak this may be an oversight as a result of the recent re-purposing of the SwitchEventProvider and the extraction of the Shield management methods into the TSService and TSManager (as part of the framework modularization as well). I will try to recreate it, but in the meanwhile, can you take a look at it? Start from the Preferences class and trace the error back to the source.

**Comment by k22mak** [comment]
@jorgesilva It appears to be an issue with line 45 in the TeclaShieldManager. I'm not entire sure of what the problem is with that line. I have a guess that it has to do with something still being bound to the service when the stopService is called. According to the stopService documentation "Note that if a stopped service still has ServiceConnection objects bound to it with the BIND_AUTO_CREATE set, it will not be destroyed until all of these bindings are removed. See the Service documentation for more details on a service's lifecycle." I will continue to look for a solution.

**Comment by tnantais** [comment]
I'm seeing this behaviour as well, and when I try to turn the checkbox back on, it can't find the shield.  It is necessary to unpair and re-pair to get everything working again.

**Comment by ijdoc** [comment]
The TeclaShieldService was being stopped without unbinding from the SwitchEventProvider... that was the reason for the leak. The message was a separate issue but will be fixed with this bug nevertheless.
