### ISSUE TITLE
Make highlight colour a preference

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#171]
With the change of the Tecla highlight from red to blue, some users may prefer to switch back to red since they may already be used to it

**Comment by sagar-chandarana** [comment]
It can be worked on. Create new checkbox preference entry in layout, TeclaPrefs and Persistence classes. Then add Red PNGs and new keyboard layouts. Use either Red or Blue layouts according to the preference.
But I don't know exactly how to create a new entry in Preferences. Tried to track an already implemented Pref, like the SpeakerPhone, but didn't get it.

**Comment by ijdoc** [comment]
You have to start by defining the preference in the preference layout xml file. Then from there you fill in the functionality.

**Comment by oranje** [comment]
We should only have a limited number colours (Blue, Red, Yellow?) To prevent users from selecting something to dark or to light that can be confusing.

**Comment by ijdoc** [comment]
After some discussion with @oranje it seems that it will make more sense to add a full set of interface customization settings to the Jelly Bean version instead (through a pluggable Tecla Framework). The Framework has already been started inside the tecla-as project here: https://github.com/idrc/tecla-as

**Comment by ijdoc** [comment]
Will close the bug here in favour of the new project for Jelly Bean: https://github.com/idrc/tecla-as/issues/45

As a general rule, new suggested features will be only considered for the Jelly Bean version. The original TeclaAccess project should only accept bug reports relating to necessary fixes and mayor usability issues.
