### ISSUE TITLE
No way to access Notification Drop Down

### ISSUE THREAD

**Issue by sagar-chandarana** [KomodoOpenLab/TeclaAccess#178]
There's no key on the navigation keyboard to access notification drop down. Even after dragging it down from the top of the screen, Notification menu is not in the focus of Tecla app.

**Comment by ijdoc** [comment]
This bug will not be fixed within the TeclaAccess project but will be addressed instead by the TeclaHighlighter (https://github.com/idrc/tecla-as) and Tecla for Jelly Bean (https://github.com/idrc/TeclaAccessJB) projects.

**Comment by ijdoc** [comment]
Closed in favour of: https://github.com/idrc/tecla-as/issues/46
