### ISSUE TITLE
Inverse scanning mode

### ISSUE THREAD

**Issue by oranje** [KomodoOpenLab/TeclaAccess#188]
In latest release inverse scanning in not working properly. Switch is pressed to star scanning and while the keyboard is scanning a command is sent (without releasing), when switch is released the selected command is sent too.

**Comment by ijdoc** [comment]
"Inverse scanning mode" does not say absolutely anything about the issue experienced. The summary should provide a clear idea of the issue being reported. A better summary would have been "Command is sent while the keyboard is scanning (without releasing) on inverse scanning mode"

This is the result of a conflict between the inverse scanning mode and the long press reset, which gets triggered right away with the default setting (3 seconds).

Marking this issue as invalid in favour of #189

**Comment by ijdoc** [comment]
"Inverse scanning mode" does not say absolutely anything about the issue experienced. The summary should provide a clear idea of the issue being reported. A better summary would have been "Command is sent while the keyboard is scanning (without releasing) on inverse scanning mode"

This is the result of a conflict between the inverse scanning mode and the long press reset, which gets triggered right away with the default setting (3 seconds).

Marking this issue as invalid in favour of #189

**Comment by ijdoc** [comment]
"Inverse scanning mode" does not say absolutely anything about the issue experienced. The summary should provide a clear idea of the issue being reported. A better summary would have been "Command is sent while the keyboard is scanning (without releasing) on inverse scanning mode"

This is the result of a conflict between the inverse scanning mode and the long press reset, which gets triggered right away with the default setting (3 seconds).

Marking this issue as invalid in favour of #189
