### ISSUE TITLE
Long press reset delay should be in general settings

### ISSUE THREAD

**Issue by oranje** [KomodoOpenLab/TeclaAccess#198]
Tecla Access 1.0
Currently the Long press reset delay setting is buried in Configure switch actions without a title, it needs to be in the General settings

**Comment by sagar-chandarana** [comment]
The long press reset delay setting is currently in General Settings in develop branch. Is this issue resolved?

**Comment by ijdoc** [comment]
yes, it should be... I might have forgotten to make the "fixes" comment
