### ISSUE TITLE
Dwell time should be extended to the first key after row selection

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#25]
From: https://bugs.launchpad.net/meadl/+bug/874382

When selecting a key, the dwell time allows for enough time to repeat keys, but this is not the case for the transition between row to key scanning and because the scanning is changed, users do not have enough time to react if they are looking to select the first key.

**Comment by elyas-bhy** [comment]
Issue already fixed (morse branch).
