### ISSUE TITLE
"Switch Event Provider" is not a user-friendly string

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#30]
Tecla shows a series of notification bar messages related to connection with the Tecla Shield, however, these messages are titled "Switch Event Provider", which is an internal app component that has no meaning to users. Consider changing the string to "Tecla Shield Status", "Tecla Shield Connection", "Switch connection status", "Alternative input status" or other more descriptive title.

**Comment by ankitdaf** [comment]
Hi

Please find the pull request to fix this here : https://github.com/jorgesilva/TeclaAccess/pull/36

**Comment by ijdoc** [comment]
@ankitdaf I pulled your fix but I realized it will be better to use "Tecla Shield Connection Status", can you add this and request another pull?

**Comment by ankitdaf** [comment]
Requested another pull. https://github.com/jorgesilva/TeclaAccess/pull/44
