### ISSUE TITLE
Speakerphone shouldn't automatically be activated when a call is answered with the Tecla Shield

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#35]
Because it may cause conflict with a bluetooth headset.

NOTE: This is a placeholder just to remember to remove that feature in case it has not yet been removed!

**Comment by rishabhjain08** [comment]
--when the phone is ringing left switch(J3) will cancel the call and switch(J4) will answer the call.
--when the phone a call is active and you press left switch then the call ends, 
right switch should produce no response(please check this fact).
--the down switch(J2) toggles speakerphone on and off.

**Comment by ijdoc** [comment]
@rishabhjain08 there is no justification for the call handling scheme you are suggesting. All of the functions we add have to be available to single switch users as well, so this is not something that can be approved at the moment. Also, your comment is beyond the scope of this issue. If you have suggestions for specific features or enhancements, please create a separate bug report for each of them so that they can be discussed separately.

**Comment by rishabhjain08** [comment]
What is the expected behavior if speaker phones are not be turned on automatically? Should they not be turned on at all or we should listen for some user input to know if the speakers are to turned on or off.

**Comment by rishabhjain08** [comment]
Changes have been made so that a call is received without turning the speakes on.
Pull request: #47

**Comment by ijdoc** [comment]
I added a related issue #54. Feature originally suggested by @rishabhjain08
