### ISSUE TITLE
Can't select apps on Samsung GT-I5800

### ISSUE THREAD

**Issue by withad** [KomodoOpenLab/TeclaAccess#42]
The Tecla app is installed and the navigation keyboard works fine for moving around in specific apps (tested with Settings, the clock, Gmail, and a few others) but not when trying to select apps on the home screen or in the main Applications list. There's no highlighting box around any of the icons and pressing OK doesn't do anything.

The phone is also known as the Samsung Galaxy 3 or the Galaxy Apollo. It's running Android 2.2, including some modifications Samsung has as standard, like Swype.

**Comment by ijdoc** [comment]
This is typical of custom Launchers that break built-in accessibility. What you need to do is the following:
1. Report the issue to Samsung (if a public ticket/report is available, post the link here)
2. Install [ADW.Launcher](https://play.google.com/store/apps/details?id=org.adw.launcher) and test again to see if that fixes the problem
3. Report the issue (and the outcome after installing another launcher) on the device compatibility wiki at http://wiki.mobile-accessibility.idrc.ocad.ca/w/Tecla_Access/Device_Compatibility

Once all of that is done and all corresponding URL references are added to this issue, we can close it.

**Comment by withad** [comment]
I can't seem to find any bug reporting system for Samsung. This [SO post](http://stackoverflow.com/questions/4928267/where-to-report-device-specific-bugs-to-samsung) suggests that there isn't one, but that reporting to the main Android project _might_ get it passed on to the manufacturers.

Installing ADW Launcher did fix it and it seems to work fine with that. I've updated the device compatibility page to reflect that.

**Comment by ijdoc** [comment]
Excellent! Thanks a lot for that. Have you reported to the main Android project? If you do, please make sure to label it as an accessibility bug, then I can pass it on directly to the Google accessibility team.

**Comment by withad** [comment]
I've now submitted it [here](http://code.google.com/p/android/issues/detail?id=27755). I'm not sure I described it perfectly, though, but I think it's okay. Hopefully someone will be able to do something about it at some point.

**Comment by ijdoc** [comment]
Ok, just flagged the bug report with the a11y team at Google, now closing the issue.
