### ISSUE TITLE
When a BT headset is connected, answering a call with Tecla does not route the audio to it.

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#54]
At all times while answering the call bluetooth headsets should be searched for first. If not available, then simply call is answered using the default fallback channel (i.e., wired headset if connected or built-in speaker/mic combo).

**Comment by rishabhjain08** [comment]
I checked on Galaxy SII, the current implementation is checking for bluetooth headsets if available and using fallback channel if bt headsets are unavailable

**Comment by ijdoc** [comment]
That actually makes sense because that would be the usual behaviour anyway. Will check on another phone and close the issue if I find the same thing.

I think I was more interested on is a preference that allows users to select a preferred channel regardless of what is connected (which I think you had already proposed). I will create an issue report for that.

**Comment by rishabhjain08** [comment]
What I meant to propose was that users currently cant access all the options provided in the call screen. They cant even cancel the call(This behavior depends from phone to phone since the call screen and button layouts is different in different phones). So I suggested to incorporate swipe recognition to decide whether to receive or reject the call.

**Comment by rishabhjain08** [comment]
Also I suggested to switch between channels(originally speaker phones but  why not bt headsets and wired headset too  ) by tapping the screen.

**Comment by ijdoc** [comment]
There are a few issues with your suggestions @rishabhjain08:
- In general, swiping is not ideal given that we are dealing with users with mobility impairment.
- Also ideally, all features of the app should be self-evident. Tapping could be used to change an audio output as you suggest, but it is unclear how we would make sure users know that this is possible.
- Tapping to change the audio output would actually change the user experience significantly. People are not expecting their actions to do something other than controlling the on-screen keyboard and this can potentially interfere with the phone dialing activity. For example, if users need to enter an extension during the call, how will they manage to override the selection of audio outputs?

Please report your suggestions on issue #57 since this one will be closed now.
