### ISSUE TITLE
Add preference to override default audio channel selection

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#57]
The usual behaviour of the system is to use a BT headset if connected, then check for wired headset and finally the built-in mic + speaker. This hierarchy makes sense except for the fact that some users may want to turn on the speakerphone instead of the built-in mic+speaker. This will likely involve overriding the default hierarchy and implementing a custom one, but it should definitely be a preference.

**Comment by rishabhjain08** [comment]
Then how should we decide the order in which the channels get selected. Should the order be asked from the user at the time of setting preferences?

**Comment by tguinot** [comment]
Used Android AudioManager methods.
Added checkbox in preferences.
https://github.com/tguinot/TeclaAccess/commit/172b79e9235922f0d9344e9b7b3ac177a96d7695
