### ISSUE TITLE
Keyboard not responding properly to switch events.

### ISSUE THREAD

**Issue by AKdroid** [KomodoOpenLab/TeclaAccess#59]
When using the Tecla Keyboard in scanning mode ,and focussed on a field to type,any switch event results in exiting the active application.This was seen when using the emulator to send events.The event being send is proper as seen in the logcat of my device.
Possibly home button is getting pressed but not sure.

**Comment by ijdoc** [comment]
A long press on any button does cause a HOME call. If you are sending the press event without sending a release, the HOME button would be called after a few seconds (~5)

**Comment by ijdoc** [comment]
You mentioned you are using a 160 as the release event, but it seems that you need to send a 0x3F. That is a 63. Either that or (very unlikely, but may work) 0x0F, which is a 15.
Just to clarify, this is a "all switches released" event.

Also, 160 would be 0xA0 or "all switches pressed" event. If this is the case, then please push the change to the emulator on the Tecla Shield project:
https://github.com/jorgesilva/TeclaShield

**Comment by AKdroid** [comment]
I noticed that a switch press event is sent as a bitmask where a logic 1 would imply a press and if a logic 0 should imply
release so i think in order to release 0xC0 i.e 11000000b should release all key events.

It sems to work.

**Comment by ijdoc** [comment]
Interesting, I thought it was the other way around. I have seen before either hardware or scripting languages inverting the logic, maybe something like this is also at play.

Thanks for your work debugging this! Looking forward to the updated version of the emulator. BTW, did you notice someone edited the README for markdown? I pulled their changes to the develop branch.

**Comment by AKdroid** [comment]
i found the source of the problem switch release is occuring first for switch 1 and and then it is getting pressed instead of getting pressed first and then releasing.

**Comment by ijdoc** [comment]
you mean the emulator is doing that? If so, can we close this issue and discuss it in the Tecla Shield project instead?

**Comment by AKdroid** [comment]
i think i got it why the apps are exiting on switch 1 press,it is not getting released i.e. till i press it again.by the time i do that it becomes a long press so home button is pressed.... :)
I just have to figure out how to release switch 1 keypress immediately
and then the emulator would be complete....

**Comment by AKdroid** [comment]
Dropping key event because targetWin event for keycode 82 is null is the warning i am getting.After this the app (here google search) closes
