### ISSUE TITLE
Dependency of Full screen switch Preferences is incorrect

### ISSUE THREAD

**Issue by rishabhjain08** [KomodoOpenLab/TeclaAccess#66]
If we switch on the full screen switch mode , we know self scanning will get selected by itself. Now if I click on inverse scanning then self scanning will get deselected and inverse self scanning will get selected automatically. Upon reaching this stage if you again click on inverse scanning then both self scanning and inverse scanning will be in deselected state and full screen switch will still be on which should not be the case.

**Comment by ijdoc** [comment]
Excellent work! Thanks!
