### ISSUE TITLE
Add a 3-key Morse Input Method

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#87]
Add a Morse Input Method (keyboard) to Tecla so Morse coders can type efficiently.

The initial implementation will provide a configurable HUD for training and the ability to assign any 3 switches to any 3 switches connected to the Shield.

This work should be done in the main project repo, in a branch called 'morse' or similar, pulling from the development branch according to the following branching model: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by ijdoc** [comment]
Just added a wiki page to document the work. It should eventually turn into a tutorial with details on how to use the feature: https://github.com/jorgesilva/TeclaAccess/wiki/Morse-Input

**Comment by elyas-bhy** [comment]
The implementation of this feature can be found in the morse branch (ready for merging / beta testing): https://github.com/jorgesilva/TeclaAccess/tree/morse

More features and options will be added soon, and wiki updates are in progress.
