### ISSUE TITLE
Re-arrange keys in the typing and the primary navigation keyboard

### ISSUE THREAD

**Issue by rishabhjain08** [KomodoOpenLab/TeclaAccess#88]
The show typing keyboard key will move to the beginning of the keyboard(navigation as well as typing keyboard). This is in response to user feedback since users have expressed it takes too many steps to close the typing keyboard after opening it by mistake. The corresponding buttons in the typing keyboard will just flip locations. That is, the hide keyboard key will be at the beginning of the last row, while the numbers and special characters key will go to the end.

**Comment by ankitdaf** [comment]
Some layouts are fixed but design looks messy, take suggestions and change proportions to fix that
