### ISSUE TITLE
Secondary navigation keyboard should have a key to skip back to the primary navigation keyboard

### ISSUE THREAD

**Issue by rishabhjain08** [KomodoOpenLab/TeclaAccess#90]
_related to issue #89_
The secondary navigation keyboard should have a key to skip back to the primary navigation keyboard, therefore it doesn't really make sense to use the Android image as a label for the _show secondary navigation keyboard_ key in the primary navigation keyboard.

**Comment by ijdoc** [comment]
This will be solved by adding an "ALT" key that makes it possible to toggle between the primary and secondary navigation keyboards. There will also be a repeat lock key as defined in issue #16
